CI
cpp-park-vk-education/2022_2_oldB pull request #1
Opened 2022-10-19 13:31 UTC by lostl1ght

2022-10-26 16:38 UTC, rkhazh requested changes

2022-10-26 16:38 UTC, rkhazh commented on .github/workflows/pull_request.yml
> +        run: ninja -C${{github.workspace}}/build
Используйте артефакты, эти команды уже были в прошлой джобе

2022-10-26 16:38 UTC, rkhazh commented on .github/workflows/pull_request.yml
> +        run: valgrind ${{github.workspace}}/build/test -- --exit=true
Желательно ставить \n в конце каждого файла. Почитайте, зачем это нужно

2022-10-30 19:54 UTC, lostl1ght commented on .github/workflows/pull_request.yml
> +        run: ninja -C${{github.workspace}}/build
Сделано.

2022-10-30 19:54 UTC, lostl1ght commented on .github/workflows/pull_request.yml
> +        run: valgrind ${{github.workspace}}/build/test -- --exit=true
Они уже стоят, просто на гитхабе не отображаются.

2022-10-31 13:41 UTC, rkhazh approved these changes
Где-то грустит один потерянный \n
А так все вроде ок

2022-10-31 13:41 UTC, rkhazh commented on .gitignore
> +.vscode/
\n

2022-10-31 14:25 UTC, lostl1ght commented on .gitignore
> +.vscode/
Упс, исправил

2022-12-22 10:03 UTC, vozvivan commented on .github/workflows/pull_request.yml
> +        run: sudo apt install lcov
точно ли нужен sudo?

2022-12-22 10:03 UTC, vozvivan commented on CMakeLists.txt
> +if (CMAKE_BUILD_TYPE MATCHES Debug)
точно корректная логика?

2022-12-22 10:03 UTC, vozvivan commented on .github/workflows/pull_request.yml
> +    runs-on: ubuntu-latest
лучше фиксировать версию

2022-12-22 10:03 UTC, vozvivan commented on .github/workflows/pull_request.yml
> +        run: chmod +x build/test/test && ./build/test/test
точно нужен chmod?

2022-12-22 10:03 UTC, vozvivan commented on .github/workflows/pull_request.yml
> +      - name: coverage
хорошо отчет тож спрятать куда-нибудь

2022-12-22 10:03 UTC, vozvivan commented on test/test_add_one.cpp
> +#include <sstream>
хм

2024-07-09 11:23 UTC, closed without merging